image: "ruby:2.5.1"

services:
  - postgres:latest

variables:
  POSTGRES_DB: ddm_be_test
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: ""

before_script:
  - apt-get update -qq && apt-get install -y -qq postgresql postgresql-contrib libpq-dev cmake nodejs
  - ruby -v
  - which ruby
  - gem install bundler --no-ri --no-rdoc
  - RAILS_ENV=test bundle install --jobs $(nproc) "${FLAGS[@]}"
  - cp config/database.yml.gitlab config/database.yml
  - RAILS_ENV=test bundle exec rake db:migrate
  - RAILS_ENV=test bundle exec rake db:seed

Test:
  script:
    - RAILS_ENV=test bundle exec rspec